name: Deploy to Azure

on:
  push:
    branches:
      - main  # Adjust this based on your branch

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.13.x'  # Adjust this based on your Flutter version

    - name: Install dependencies
      run: flutter pub get

#    - name: build runner
#      run: flutter pub run build_runner build --delete-conflicting-outputs

    - name: Build web
      run: flutter build web --release

    - name: Install Azure cli
      run: |
        sudo apt-get install ca-certificates curl apt-transport-https lsb-release gnupg
        curl -sL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/microsoft.gpg > /dev/null
        AZ_REPO=$(lsb_release -cs)
        echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" | sudo tee /etc/apt/sources.list.d/azure-cli.list
        sudo apt-get update
        sudo apt-get install azure-cli

    - name: show az version
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az version

    - name: Az CLI login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'Flutter demo'
        slot-name: 'production'
        package: build/web
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_ccad52081eee40179254c52e68e2a489 }}
