name: Deploy to Azure

on:
  push:
    branches:
      - main  # Adjust this based on your branch

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.13.x'  # Adjust this based on your Flutter version

    - name: Install dependencies
      run: flutter pub get

#    - name: build runner
#      run: flutter pub run build_runner build --delete-conflicting-outputs

    - name: Az CLI login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'DeveraFitness'
        slot-name: 'production'
        package: 'build/web/**'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_ccad52081eee40179254c52e68e2a489 }}
